# Generated by Django 3.2.5 on 2021-07-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=350)),
                ('version', models.CharField(max_length=15, unique=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
