# Generated by Django 3.2.5 on 2021-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='description',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='short_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
